version: 0.0
os: linux
files:
  - source: /api/doc
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_container
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_container
      timeout: 300
      runas: root
